function obj = node(body, utc, dv, ParentPath, ChildNum)
if nargin == 0 
    body = NaN; utc = datetime; dv = NaN; 
    ParentPath = NaN; ChildNum = NaN; 
end

obj = struct(...
    'ID', body, ...
    'Date', utc, ...
    'J', 0, ...
    'Budget', dv, ...
    'PathTo', [ParentPath ChildNum] ...
    );
end